version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ubuntu/app
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: deploy-before.sh
      runas: ubuntu
  # AfterInstall:
    # - location: backend/mogether/scripts/stop.sh
      # timeout: 60
  ApplicationStart:
    - location: scripts/start.sh
    # - location: backend/mogether/scrpits/start.sh
      timeout: 60
      runas: ubuntu
