version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ubuntu/app/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  # AfterInstall:
    # - location: backend/mogether/scripts/stop.sh
      # timeout: 60
  ApplicationStart:
    - location: backend/mogether/scrpits/deploy.sh
      timeout: 60
