name: CI/CD Pipeline for mogether

on:
  push:
    branches:
      - test

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Cache Node.js dependencies
        uses: actions/cache@v2
        with:
          path: frontend/mogether/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/mogether/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        working-directory: ./frontend/mogether
        run: npm install

      - name: Build the project
        working-directory: ./frontend/mogether
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_2 }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_2 }}
          aws-region: ap-northeast-2

      - name: Deploy to S3
        run: aws s3 sync ./frontend/mogether/build s3://mo-gether-front --delete

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"