name: Backend CICD
run-name: Running
on:
  push:
    branches:
      - sungmin
env:
  AWS_REGION: ap-northeast-2
  AWS_S3_BUCKET: moim-image
  AWS_CODE_DEPLOY_APPLICATION: mogether-cd
  AWS_CODE_DEPLOY_GROUP: mogether-cd-group

jobs:
  build-with-gradle:
    runs-on: ubuntu-latest
    
    steps:
    - name: sungmin branch로 이동
      uses: actions/checkout@v3
      with:
        ref: sungmin
    - name: Install JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
    - name: gradlew에 실행 권한 부여
      run: cd backend/mogether && chmod +x ./gradlew
    - name: Build with Gradle
      run: cd backend/mogether && ./gradlew clean build
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
    - name: S3에 업로드
      run: aws deploy push --application-name ${{ env.AWS_CODE_DEPLOY_APPLICATION }} --ignore-hidden-files --s3-location s3://$AWS_S3_BUCKET/cicdtest/$GITHUB_SHA.zip --source .
    - name: EC2에 배포
      run: aws deploy create-deployment --application-name ${{ env.AWS_CODE_DEPLOY_APPLICATION }} --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name ${{ env.AWS_CODE_DEPLOY_GROUP }} --s3-location bucket=$AWS_S3_BUCKET,key=cicdtest/$GITHUB_SHA.zip,bundleType=zip
